services:
  postgres:
    image: postgres:latest
    container_name: cimplico_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: cimplico_backend
    ports:
      - '4000:4000'
      - '5555:5555'
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
    container_name: cimplico_frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

volumes:
  db_data:
